// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnLzPzeKapuEWtRhwcvicOP9uYJlcfCE4',
    appId: '1:841915801580:web:36811ac258bcda65442ac9',
    messagingSenderId: '841915801580',
    projectId: 'autohut-60d7a',
    authDomain: 'autohut-60d7a.firebaseapp.com',
    storageBucket: 'autohut-60d7a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJQi_RfuAMCeWcQmpWmpJiN1EGdtEMgV4',
    appId: '1:841915801580:android:448ddd41259458c1442ac9',
    messagingSenderId: '841915801580',
    projectId: 'autohut-60d7a',
    storageBucket: 'autohut-60d7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo7l0sc9Ippy797Q_oAjOsRBhDu0hLPHI',
    appId: '1:841915801580:ios:06f0b7876cad3ef4442ac9',
    messagingSenderId: '841915801580',
    projectId: 'autohut-60d7a',
    storageBucket: 'autohut-60d7a.firebasestorage.app',
    iosBundleId: 'com.example.autohut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo7l0sc9Ippy797Q_oAjOsRBhDu0hLPHI',
    appId: '1:841915801580:ios:06f0b7876cad3ef4442ac9',
    messagingSenderId: '841915801580',
    projectId: 'autohut-60d7a',
    storageBucket: 'autohut-60d7a.firebasestorage.app',
    iosBundleId: 'com.example.autohut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnLzPzeKapuEWtRhwcvicOP9uYJlcfCE4',
    appId: '1:841915801580:web:0b0d4cfd53231794442ac9',
    messagingSenderId: '841915801580',
    projectId: 'autohut-60d7a',
    authDomain: 'autohut-60d7a.firebaseapp.com',
    storageBucket: 'autohut-60d7a.firebasestorage.app',
  );

}